### ISSUE TITLE
music generator GUI Error

### ISSUE THREAD

**Issue by tadroidho** [Shoxie12/MCDJ#8] opened 2020-11-05 07:28 UTC
Fatal bug found in the Music Generator block. Crash occurs when string type text is entered in the number input field. Please make it impossible to enter values ​​other than numbers.
Version checked at 1.12.2.
`// This doesn't make any sense!

Time: 2020-11-05 16:17:52 KST
Description: Updating screen events

java.lang.NumberFormatException: For input string: "0e"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at com.shoxie.mcdj.gui.TextFieldMusicGenerator.syncid(TextFieldMusicGenerator.java:54)
    at com.shoxie.mcdj.gui.TextFieldMusicGenerator.writeText(TextFieldMusicGenerator.java:46)
    at net.minecraft.client.gui.GuiTextField.textboxKeyTyped(SourceFile:349)
    at com.shoxie.mcdj.gui.TextFieldMusicGenerator.textboxKeyTyped(TextFieldMusicGenerator.java:32)
    at com.shoxie.mcdj.gui.GuiMusicGenerator.keyTyped(GuiMusicGenerator.java:70)
    at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:558)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:512)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:`

**Comment by Shoxie12** [comment] 2020-11-06 08:39
Duplicate of #6

**Closed as completed** 2020-11-08 23:35 UTC
Labels: bug, duplicate
